### ISSUE TITLE
Ayuda

### ISSUE THREAD

**Issue by duhamelgm** [AdrianFagilde/Grafos-Ponderados-Dirigidos#1]
@AdrianFagilde pa pero invite al repositorio

**Comment by duhamelgm** [comment]
Ping @AdrianFagilde

**Comment by YisusJe** [comment]
@duhamelgm ya casi pa

**Comment by YisusJe** [comment]
@AdrianFagilde puedes ayudarme con este problema?

**Comment by AdrianFagilde** [comment]
ta listo pa
